### ISSUE TITLE
Implement Devise methods on the Product model

### ISSUE THREAD

**Issue by kobione** [LARailsLearners/_first_app_instructions#10]
#### Understand Devise by Using its methods on the Product model**
- Create a **Products resource** using scaffolding with the following attributes:
  
  ```
  name:string description:text price:float
  ```

This scaffold will create the product controller, model, multiple views and several other files.
# 
##### http://www.gotealeaf.com/blog/how-to-use-devise-in-rails-for-authentication
- Require the user to be _logged in_ to access all the Product views
- Display `current_user` anywhere.
- Use one other method
- Make a comment below (Start using Github to work with the team.)

**Comment by jendiamond** [comment]
## Difficulty Level 3

**Comment by kangkyu** [comment]
Hello!

**Comment by kangkyu** [comment]
how different using Decimal from Float?
