### ISSUE TITLE
Associate the User and Product table

### ISSUE THREAD

**Issue by raysango** [LARailsLearners/_first_app_instructions#11]
As a user 
when I create a product 
it should appear in my product index view by adding user_id filed to the Product table
## 

https://groups.google.com/forum/#!topic/railslearners/l-xotvy63zY

Hey all,

Here is this week's assignment:
Homework #5:  "Give only a signed-in user the ability to add products and edit only their products." [Thanks Mark.]

I suggest that for those who can do the assignment above, do not read the steps below.  For those who want a little more help, here are the steps I would take to do it.  It is actually not a lot of code, but a whole lot of understanding what is going on, soooo.... make sure you take the time to learn and understand the steps.  

I am not giving you code this time, but you can use these steps to figure out what the code should be:

Homework #5:
(1) Associate User and Product tables (the models)
     - Each product should have been created by a User

(2) When creating a new product listing, make sure that there is a User associated with a newly created Product
    Hints:
    Part 1: Make sure that a User is first logged in.
    Part 2: Use Devise's "current_user" method, to get the current_user's information, to save as part of the new Product record
    Part 3: You will need to alter the Product model
    Part 4: Using the controller, you will save some user data in the product model

(3) Make sure only the signed-in user can create a Product.
    Hints:
    - (If you've done above) if there is no User, you may get an error (you will either get an error, or simply have missing data) if trying to create a Product without a User.
    - Use Devise to make sure you can only create a Product if there is a signed-in User

   Important: Edit:: (Now, work in _EDIT_ functionality):
   Currently (at this stage) ANY signed in user, can edit any product.  Let's fix that...
- Make sure only the User that created the Product, can edit their own Product.
- Use the data you have (Hint: the User data you are storing in the Product model) to only allow a the User who created the Product to edit their own product entry.
   -> This is probably best accomplished using a Devise method.
- Extra Little Bonus: On the Product page(s), display some sort of information that indicates which User created that Product (use a Devise method) 

Good luck!

Kobi

**Comment by kangkyu** [comment]
http://meetu.ps/2JSHLm Let's homework!

**Comment by kangkyu** [comment]
https://groups.google.com/forum/#!topic/railslearners/l-xotvy63zY

**Comment by kangkyu** [comment]
I share this commit - Monday group worked on today: https://github.com/LARailsLearners/kangkyu_new_app/tree/ec87f0cfd0a52f2fb763e4d45d2b98032d5445ed
