### ISSUE TITLE
Install Bootstrap

### ISSUE THREAD

**Issue by jendiamond** [LARailsLearners/_first_app_instructions#3]
### Install and understand Bootstrap an what it provides you with

"[Bootstrap](http://getbootstrap.com/), a sleek, intuitive, and powerful mobile first front-end framework for faster and easier web development."

> Bootstrap is a framework that makes it easy for a developer to create a nice design for a website or web application. There are predefined css classes for creating common components such as widgets, typography elements, lists, forms, and more. The framework also provides Javascript which makes it easy to create things like modals, popovers, scrollspies, accordions, and more. Their documentation is very thorough, providing example code for most, if not all of the components that Bootstrap provides. ~ [Go Tea Leaf](http://www.gotealeaf.com/blog/integrating-rails-and-bootstrap-part-1)
#### _(You could also use Foundation, or some other CSS framework.)_

**Take the time to learn:**
- What Bootstrap gives you. All the layout options that come included are
  awesome and make building functional websites (will buttons, Navbars,
  Dropdowns, icons, and labels, etc.) pretty damn good looking and easy it
  build. Get a sense of all the Lego pieces that come in the box!
- Understand the logic behind the "grid system" and how it help you organize
  your "views," so the way Bootstrap classes lays things out, makes sense to
  you. 

**Some possibly helpful Links:**  
- https://rubygems.org/gems/sass/versions/3.4.14
- https://rubygems.org/gems/bootstrap-sass/versions/3.3.4.1
- https://github.com/twbs/bootstrap-sass
- https://www.youtube.com/watch?v=4zMgLzfprqo
- http://www.gotealeaf.com/blog/integrating-rails-and-bootstrap-part-1
- http://leveluptuts.com/tutorials/sass-tutorials
- https://github.com/twbs/bootstrap-sass

**Comment by jendiamond** [comment]
## Difficulty Level 2

**Comment by kangkyu** [comment]
:rocket:
