### ISSUE TITLE
Install Postgres Database

### ISSUE THREAD

**Issue by jendiamond** [LARailsLearners/_first_app_instructions#5]

**Comment by jendiamond** [comment]
## Difficulty Level 5

**Comment by ahimsauzi** [comment]
If you are on a mac you can use Homebrew and install Postgress with a single command. Check it out [here](http://www.moncefbelyamani.com/how-to-install-postgresql-on-a-mac-with-homebrew-and-lunchy/)

**Comment by choimichael** [comment]
Nice to meet with you all
Personally I use a mac but I found this on youtube for windows:
Beginners PostgreSQL database Tutorial 1 - Installing and Setting up PostgreSQL ( pgAdmin ) https://www.youtube.com/watch?v=ghTksCsFBcI

Also here's an interesting video postgresql vs mysql:
https://www.youtube.com/watch?v=emgJtr9tIME
After watching the video checkout the comments below to see what other's are saying about it.
Hope this helps.
